### ISSUE TITLE
Proposing change of repo title and title in readme to use Upfront Theme Manager

### ISSUE THREAD

**Issue by josephfusco** [bappi-d-great/reset-wpmu-upfront-themes#3]

**Comment by bappi-d-great** [comment]
Thanks for the suggestion :) Done!

**Comment by josephfusco** [comment]
![screen shot 2016-03-30 at 12 08 48 pm](https://cloud.githubusercontent.com/assets/6676674/14149037/31e13f50-f670-11e5-838d-0ea01a89bf80.png)
Still showing the old name for me. :cry:
